# Generated by Django 3.1.13 on 2021-10-13 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0078_auto_20211010_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.AlterField(
            model_name='newspost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 16, 26, 2, 19337, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='name',
            field=models.CharField(default='post', max_length=100),
        ),
    ]
