# Generated by Django 3.1.13 on 2021-10-17 18:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0079_auto_20211015_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 18, 46, 53, 866283, tzinfo=utc)),
        ),
    ]
