# Generated by Django 3.1.13 on 2021-10-13 16:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0080_auto_20211013_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='how_do_you_know_about',
        ),
        migrations.AlterField(
            model_name='newspost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 16, 33, 43, 443288, tzinfo=utc)),
        ),
    ]
