# Generated by Django 3.1.13 on 2021-10-13 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0081_auto_20211013_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cover_letter',
            new_name='speech_abstract',
        ),
        migrations.AlterField(
            model_name='newspost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 16, 44, 47, 267040, tzinfo=utc)),
        ),
    ]
