# Generated by Django 3.1.13 on 2021-10-13 17:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0084_auto_20211013_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gives_a_speech',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 17, 14, 35, 104368, tzinfo=utc)),
        ),
    ]
