# Generated by Django 3.1.13 on 2021-10-13 17:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0085_auto_20211013_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invoice_data',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.TextField(default='+48 ', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wants_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 17, 40, 46, 923167, tzinfo=utc)),
        ),
    ]
