# Generated by Django 3.1.13 on 2021-10-13 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0087_auto_20211013_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gives_a_speech',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='speech_abstract',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wants_invoice',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invoice',
            field=models.CharField(blank=True, choices=[('0', 'NIE'), ('1', 'TAK')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 18, 19, 59, 272208, tzinfo=utc)),
        ),
    ]
