# Generated by Django 3.1.13 on 2021-10-13 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0090_auto_20211013_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 18, 25, 17, 792186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='invoice',
            field=models.CharField(choices=[('0', 'NIE'), ('1', 'TAK')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.CharField(default='', max_length=100),
        ),
    ]
