# Generated by Django 3.1.13 on 2021-10-13 18:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0092_auto_20211013_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 18, 33, 4, 794794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='invoice',
            field=models.CharField(blank=True, choices=[('0', 'NIE'), ('1', 'TAK')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
