# Generated by Django 3.1.13 on 2021-10-19 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0081_auto_20211019_2209'),
        ('wwwapp', '0093_auto_20211013_2033'),
    ]

    operations = [
    ]
