# Generated by Django 3.1.13 on 2021-10-19 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0094_auto_20211019_2137'),
        ('wwwapp', '0079_auto_20211015_0205'),
    ]

    operations = [
    ]
