# Generated by Django 3.1.13 on 2021-10-19 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0095_merge_20211019_2150'),
        ('wwwapp', '0094_merge_20211019_2229'),
    ]

    operations = [
    ]
